import { afterEach, describe, expect, it, vi } from 'vitest';
import { recordWorkflowEngineeringReview, WORKFLOW_ENGINEERING_REVIEW_WRITE_FUNCTION } from '@/lib/server/workflowEngineeringReview';
const original={emails:process.env.INTERNAL_ORCHESTRATOR_ALLOWED_EMAILS,roles:process.env.INTERNAL_ORCHESTRATOR_ALLOWED_ROLES};
afterEach(()=>{process.env.INTERNAL_ORCHESTRATOR_ALLOWED_EMAILS=original.emails;process.env.INTERNAL_ORCHESTRATOR_ALLOWED_ROLES=original.roles;});
const input={planV2RunId:'11111111-1111-4111-8111-111111111111',planV2DigestSha256:'a'.repeat(64),recommendationId:`rec_${'b'.repeat(64)}`,disposition:'accepted' as const,capabilityScope:'workflow_specific' as const,reviewerRationale:'Reviewed for backlog only.'};
const actor={id:'33333333-3333-4333-8333-333333333333',email:'reviewer@example.com',role:'member'};
describe('engineering review write seam',()=>{
 it('derives reviewer identity and request digest, then calls the sole RPC once',async()=>{process.env.INTERNAL_ORCHESTRATOR_ALLOWED_EMAILS=actor.email;delete process.env.INTERNAL_ORCHESTRATOR_ALLOWED_ROLES;const rpc=vi.fn().mockResolvedValue({data:{review_id:'22222222-2222-4222-8222-222222222222',review_version:1,repository_commit_sha:'c'.repeat(40),inserted:true},error:null});const result=await recordWorkflowEngineeringReview(input,actor,{admin:{rpc}});expect(result.ok).toBe(true);expect(rpc).toHaveBeenCalledTimes(1);expect(rpc.mock.calls[0]![0]).toBe(WORKFLOW_ENGINEERING_REVIEW_WRITE_FUNCTION);expect(rpc.mock.calls[0]![1].p_reviewer_actor_id).toBe(actor.id);expect(rpc.mock.calls[0]![1].p_review_request_digest_sha256).toMatch(/^[a-f0-9]{64}$/);});
 it('fails closed before persistence for unauthorized reviewers and body actor fields',async()=>{delete process.env.INTERNAL_ORCHESTRATOR_ALLOWED_EMAILS;delete process.env.INTERNAL_ORCHESTRATOR_ALLOWED_ROLES;const rpc=vi.fn();expect(await recordWorkflowEngineeringReview(input,actor,{admin:{rpc}})).toEqual({ok:false,code:'reviewer_not_eligible'});process.env.INTERNAL_ORCHESTRATOR_ALLOWED_EMAILS=actor.email;expect((await recordWorkflowEngineeringReview({...input,reviewerActorId:actor.id},actor,{admin:{rpc}})).ok).toBe(false);expect(rpc).not.toHaveBeenCalled();});
});
