import type { ClausePatternDefinition } from '@/lib/contracts/types';

export const CLAUSE_PATTERN_LIBRARY_V1: ClausePatternDefinition[] = [
  {
    pattern_id: 'execution_based_term',
    pattern_name: 'Execution-Based Term',
    family: 'execution_based_term',
    trigger_phrases: ['from execution', 'from the date of execution', 'effective for', 'term of this contract'],
    semantic_slots: ['executed_date', 'effective_date', 'initial_term_length', 'expiration_date'],
    document_zones: ['body', 'general_conditions', 'signature_pages'],
    confidence_rules: ['execution_anchor_plus_duration_clause'],
    conflict_rules: ['effective_date_and_execution_date_diverge_without_explanation'],
    question_rules: ['confirm_derived_expiration_date'],
    example_variants: [
      'The initial term shall be one year from the date of execution.',
      'This Agreement is effective for ninety (90) days from execution.',
    ],
  },
  {
    pattern_id: 'ntp_activation',
    pattern_name: 'Notice To Proceed Activation',
    family: 'ntp_activation',
    trigger_phrases: ['notice to proceed', 'written notice to proceed', 'issuance of notice to proceed'],
    semantic_slots: ['activation_trigger_type', 'authorization_required', 'performance_start_basis', 'mobilization_sla'],
    document_zones: ['body', 'scope_attachment', 'general_conditions'],
    confidence_rules: ['ntp_phrase_near_commencement_language'],
    conflict_rules: ['effective_date_equals_work_start_without_ntp_resolution'],
    question_rules: ['resolve_activation_trigger'],
    example_variants: [
      'Contractor shall commence work only upon written Notice to Proceed.',
      'Mobilization shall occur within 72 hours of the Notice to Proceed.',
    ],
  },
  {
    pattern_id: 'task_order_activation',
    pattern_name: 'Task Order Activation',
    family: 'task_order_activation',
    trigger_phrases: ['task order', 'work order', 'written authorization', 'issued by work order'],
    semantic_slots: ['activation_trigger_type', 'authorization_required', 'performance_start_basis'],
    document_zones: ['body', 'scope_attachment', 'general_conditions'],
    confidence_rules: ['task_order_phrase_near_scope_or_start_language'],
    conflict_rules: ['task_order_required_but_work_treated_as_auto_authorized'],
    question_rules: ['resolve_activation_trigger'],
    example_variants: [
      'Services shall be authorized by written task order.',
      'No work may begin until a work order is issued by the County.',
    ],
  },
  {
    pattern_id: 'disaster_triggered_activation',
    pattern_name: 'Disaster-Triggered Activation',
    family: 'disaster_triggered_activation',
    trigger_phrases: ['declaration of emergency', 'declared disaster', 'storm event', 'catastrophic event'],
    semantic_slots: ['activation_trigger_type', 'performance_start_basis'],
    document_zones: ['body', 'scope_attachment'],
    confidence_rules: ['disaster_trigger_phrase_near_activation_language'],
    conflict_rules: ['activation_assumed_without_disaster_trigger_status'],
    question_rules: ['resolve_activation_trigger'],
    example_variants: [
      'Services may be activated following a declared disaster event.',
      'Work is contingent upon declaration of emergency by the Owner.',
    ],
  },
  {
    pattern_id: 'renewal_option',
    pattern_name: 'Renewal Option',
    family: 'renewal_option',
    trigger_phrases: ['option to renew', 'renew for', 'extension option'],
    semantic_slots: ['initial_term_length'],
    document_zones: ['body', 'general_conditions'],
    confidence_rules: ['renewal_phrase_near_term_language'],
    conflict_rules: ['renewal_treated_as_automatic'],
    question_rules: ['confirm_initial_term_length'],
    example_variants: ['The County may renew this Agreement for two additional one-year terms.'],
  },
  {
    pattern_id: 'unit_rate_schedule',
    pattern_name: 'Unit Rate Schedule',
    family: 'unit_rate_schedule',
    trigger_phrases: ['unit rates', 'rate schedule', 'exhibit a', 'time-and-materials rates'],
    semantic_slots: ['rate_schedule_present', 'rate_schedule_pages', 'pricing_applicability'],
    document_zones: ['pricing_table', 'exhibit', 'body'],
    confidence_rules: ['grounded_pricing_table_or_rate_section_signal'],
    conflict_rules: ['rate_schedule_present_without_applicability_resolution'],
    question_rules: ['resolve_pricing_applicability'],
    example_variants: [
      'Compensation shall be based on the unit prices set forth in Exhibit A.',
      'Emergency debris removal unit rates and time-and-materials rates.',
    ],
  },
  {
    pattern_id: 'not_to_exceed',
    pattern_name: 'Not To Exceed',
    family: 'not_to_exceed',
    trigger_phrases: ['not to exceed', 'shall not exceed', 'maximum amount payable'],
    semantic_slots: ['contract_ceiling'],
    document_zones: ['body', 'pricing_table'],
    confidence_rules: ['nte_phrase_plus_currency_value'],
    conflict_rules: ['unit_rate_cap_misread_as_total_ceiling'],
    question_rules: ['confirm_contract_ceiling'],
    example_variants: ['The total amount payable under this Agreement shall not exceed $30,000,000.'],
  },
  {
    pattern_id: 'no_guarantee_quantity',
    pattern_name: 'No Guarantee Quantity',
    family: 'no_guarantee_quantity',
    trigger_phrases: ['no guarantee', 'no minimum amount of work', 'no guaranteed quantity'],
    semantic_slots: ['no_guarantee_quantity'],
    document_zones: ['body', 'pricing_table'],
    confidence_rules: ['no_minimum_work_phrase_match'],
    conflict_rules: ['estimated_volume_treated_as_commitment'],
    question_rules: ['confirm_no_guarantee_quantity'],
    example_variants: ['Nothing in this Agreement shall be construed to guarantee any minimum amount of work.'],
  },
  {
    pattern_id: 'pass_through_disposal',
    pattern_name: 'Pass-Through Disposal',
    family: 'pass_through_disposal',
    trigger_phrases: ['pass through', 'passthrough', 'tipping fee', 'disposal fee', 'landfill fee'],
    semantic_slots: ['disposal_fee_treatment', 'pricing_applicability'],
    document_zones: ['pricing_table', 'exhibit', 'body'],
    confidence_rules: ['disposal_fee_phrase_near_pricing_language'],
    conflict_rules: ['disposal_fee_mixed_into_unit_rate'],
    question_rules: ['resolve_disposal_fee_treatment', 'resolve_pricing_applicability'],
    example_variants: [
      'Tipping fee - vegetative - pass through.',
      'Landfill charges shall be reimbursed as pass-through costs.',
    ],
  },
  {
    pattern_id: 'monitoring_dependency',
    pattern_name: 'Monitoring Dependency',
    family: 'monitoring_dependency',
    trigger_phrases: ['monitoring', 'debris monitor', 'validated by the monitor'],
    semantic_slots: ['monitoring_required', 'billing_documentation_required'],
    document_zones: ['body', 'scope_attachment', 'payment_terms'],
    confidence_rules: ['monitoring_phrase_near_payment_or_ticket_language'],
    conflict_rules: ['payment_allowed_without_monitor_validation'],
    question_rules: ['confirm_monitoring_requirement'],
    example_variants: ['All haul tickets must be verified by the debris monitor.'],
  },
  {
    pattern_id: 'ticket_load_documentation',
    pattern_name: 'Ticket And Load Documentation',
    family: 'ticket_load_documentation',
    trigger_phrases: ['load ticket', 'haul ticket', 'truck certification', 'manifest', 'tower log'],
    semantic_slots: ['billing_documentation_required'],
    document_zones: ['body', 'payment_terms', 'scope_attachment'],
    confidence_rules: ['documentation_phrase_near_invoice_support_language'],
    conflict_rules: ['documentation_requirement_left_implicit'],
    question_rules: ['confirm_billing_documentation_requirements'],
    example_variants: ['Invoices shall include all load tickets, manifests, and truck certifications.'],
  },
  {
    pattern_id: 'fema_eligibility_restriction',
    pattern_name: 'FEMA Eligibility Restriction',
    family: 'fema_eligibility_restriction',
    trigger_phrases: ['fema eligible', 'eligibility', 'ineligible work', 'reimbursable by fema'],
    semantic_slots: ['fema_eligibility_gate', 'pricing_applicability', 'billing_documentation_required'],
    document_zones: ['body', 'payment_terms', 'compliance'],
    confidence_rules: ['fema_phrase_near_payment_or_scope_restriction'],
    conflict_rules: ['ineligible_work_treated_as_billable'],
    question_rules: ['resolve_fema_eligibility_gate'],
    example_variants: ['Payment is limited to FEMA-eligible work and documented eligible costs.'],
  },
  {
    pattern_id: 'mobilization_deadline',
    pattern_name: 'Mobilization Deadline',
    family: 'mobilization_deadline',
    trigger_phrases: ['mobilize within', 'mobilization within', 'respond within'],
    semantic_slots: ['mobilization_sla', 'performance_start_basis'],
    document_zones: ['body', 'scope_attachment'],
    confidence_rules: ['deadline_phrase_plus_duration_value'],
    conflict_rules: ['deadline_anchored_to_wrong_trigger'],
    question_rules: ['confirm_mobilization_deadline'],
    example_variants: ['Contractor shall mobilize within 24 hours of Notice to Proceed.'],
  },
  {
    pattern_id: 'insurance_bond_requirements',
    pattern_name: 'Insurance And Bond Requirements',
    family: 'insurance_bond_requirements',
    trigger_phrases: ['insurance', 'bond', 'performance bond', 'payment bond'],
    semantic_slots: [],
    document_zones: ['general_conditions', 'compliance'],
    confidence_rules: ['insurance_or_bond_phrase_match'],
    conflict_rules: [],
    question_rules: [],
    example_variants: ['Contractor shall maintain insurance and furnish performance and payment bonds.'],
  },
  {
    pattern_id: 'subcontract_controls',
    pattern_name: 'Subcontract Controls',
    family: 'subcontract_controls',
    trigger_phrases: ['subcontract', 'subcontractor', 'prior written approval'],
    semantic_slots: [],
    document_zones: ['general_conditions', 'compliance'],
    confidence_rules: ['subcontract_phrase_match'],
    conflict_rules: ['subcontractor_name_treated_as_prime_contractor'],
    question_rules: [],
    example_variants: ['Subcontracting is subject to prior written approval of the Owner.'],
  },
  {
    pattern_id: 'audit_record_retention',
    pattern_name: 'Audit And Record Retention',
    family: 'audit_record_retention',
    trigger_phrases: ['retain records', 'record retention', 'audit', 'access to records'],
    semantic_slots: ['billing_documentation_required', 'fema_eligibility_gate'],
    document_zones: ['general_conditions', 'payment_terms', 'compliance'],
    confidence_rules: ['audit_phrase_match'],
    conflict_rules: [],
    question_rules: [],
    example_variants: ['Contractor shall retain records for audit and reimbursement review.'],
  },
  {
    pattern_id: 'termination_convenience_or_cause',
    pattern_name: 'Termination For Convenience Or Cause',
    family: 'termination_convenience_or_cause',
    trigger_phrases: ['terminate for convenience', 'terminate for cause', 'default'],
    semantic_slots: [],
    document_zones: ['general_conditions'],
    confidence_rules: ['termination_phrase_match'],
    conflict_rules: [],
    question_rules: [],
    example_variants: ['The Owner may terminate this Agreement for convenience or for cause.'],
  },
];

export const CLAUSE_PATTERN_LIBRARY_V1_BY_ID = new Map(
  CLAUSE_PATTERN_LIBRARY_V1.map((pattern) => [pattern.pattern_id, pattern] as const),
);
