import type {
  ContractCoverageDefinition,
  ContractDocumentTypeProfile,
} from '@/lib/contracts/types';

export const COVERAGE_LIBRARY_V1: Record<ContractDocumentTypeProfile, ContractCoverageDefinition[]> = {
  fema_disaster_recovery_debris_contract: [
    {
      coverage_id: 'term_trigger',
      family: 'term_and_activation',
      clause_family: 'execution_based_term',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'partial',
      downstream_dependency: ['decisioning', 'workflow_generation', 'operator_review'],
      operator_review_if: ['missing', 'weak', 'derived', 'conflicted'],
    },
    {
      coverage_id: 'activation_trigger',
      family: 'term_and_activation',
      clause_family: 'activation_dependency',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'partial',
      downstream_dependency: ['activation', 'decisioning', 'workflow_generation', 'operator_review'],
      operator_review_if: ['missing', 'weak', 'conditional', 'conflicted'],
    },
    {
      coverage_id: 'pricing_schedule',
      family: 'pricing_and_payment',
      clause_family: 'unit_rate_schedule',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'strong',
      downstream_dependency: ['decisioning', 'billing_review', 'workflow_generation'],
      operator_review_if: ['missing', 'weak', 'conflicted'],
    },
    {
      coverage_id: 'pricing_applicability',
      family: 'pricing_and_payment',
      clause_family: 'pricing_applicability',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'partial',
      downstream_dependency: ['decisioning', 'billing_review', 'reimbursement_logic', 'operator_review'],
      operator_review_if: ['missing', 'weak', 'conditional', 'conflicted'],
    },
    {
      coverage_id: 'scope_categories',
      family: 'scope_and_services',
      clause_family: 'scope_categories',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'partial',
      downstream_dependency: ['decisioning', 'billing_review', 'operator_review'],
      operator_review_if: ['missing', 'weak'],
    },
    {
      coverage_id: 'documentation_prerequisites',
      family: 'documentation_and_compliance',
      clause_family: 'ticket_load_documentation',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'partial',
      downstream_dependency: ['billing_review', 'reimbursement_logic', 'operator_review'],
      operator_review_if: ['missing', 'weak', 'conditional'],
    },
    {
      coverage_id: 'monitoring_dependency',
      family: 'documentation_and_compliance',
      clause_family: 'monitoring_dependency',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'partial',
      downstream_dependency: ['billing_review', 'reimbursement_logic', 'operator_review'],
      operator_review_if: ['missing', 'weak', 'conditional'],
    },
    {
      coverage_id: 'fema_eligibility',
      family: 'documentation_and_compliance',
      clause_family: 'fema_eligibility_restriction',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'partial',
      downstream_dependency: ['decisioning', 'billing_review', 'reimbursement_logic', 'operator_review'],
      operator_review_if: ['missing', 'weak', 'conditional', 'conflicted'],
    },
    {
      coverage_id: 'contract_ceiling',
      family: 'pricing_and_payment',
      clause_family: 'not_to_exceed',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'partial',
      downstream_dependency: ['decisioning', 'billing_review', 'workflow_generation'],
      operator_review_if: ['missing', 'weak', 'conflicted'],
    },
    {
      coverage_id: 'contractor_identity_consistency',
      family: 'contract_formation',
      clause_family: 'contractor_identity_consistency',
      expected_for_doc_type: true,
      criticality: 'P1',
      minimum_extraction_quality: 'strong',
      downstream_dependency: ['decisioning', 'billing_review', 'operator_review'],
      operator_review_if: ['missing', 'weak', 'conflicted'],
    },
  ],
};
