import type {
  ContractObjectFamily,
  LanguageEngineFieldDefinition,
} from '@/lib/contracts/types';

export const LANGUAGE_ENGINE_FIELDS_V1: Record<ContractObjectFamily, LanguageEngineFieldDefinition[]> = {
  contract_identity: [
    {
      field_id: 'contractor_name',
      label: 'Contractor Name',
      object_family: 'contract_identity',
      value_type: 'text',
      aliases: ['vendor_name', 'contractor', 'service provider', 'prime contractor'],
      states_allowed: ['explicit', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['decisioning', 'billing_review', 'operator_review'],
      confidence_rules: ['opening_clause_party_block', 'signature_block_party_match', 'typed_vendor_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_contractor_identity', 'resolve_conflicting_contractor_identity'],
    },
    {
      field_id: 'owner_name',
      label: 'Client Name',
      object_family: 'contract_identity',
      value_type: 'text',
      aliases: ['owner', 'county', 'city', 'applicant_name'],
      states_allowed: ['explicit', 'conflicted', 'missing_critical'],
      criticality: 'P2',
      downstream_dependency: ['decisioning', 'operator_review'],
      confidence_rules: ['opening_clause_owner_block', 'government_entity_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_owner_identity'],
    },
    {
      field_id: 'contract_number',
      label: 'Contract Number',
      object_family: 'contract_identity',
      value_type: 'text',
      aliases: ['contract no', 'agreement number', 'contract id'],
      states_allowed: ['explicit', 'conflicted', 'missing_critical'],
      criticality: 'P2',
      downstream_dependency: ['decisioning', 'operator_review'],
      confidence_rules: ['labeled_contract_number_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_contract_number'],
    },
    {
      field_id: 'solicitation_number',
      label: 'Solicitation Number',
      object_family: 'contract_identity',
      value_type: 'text',
      aliases: ['rfp number', 'bid number', 'solicitation no'],
      states_allowed: ['explicit', 'conflicted', 'missing_critical'],
      criticality: 'P3',
      downstream_dependency: ['operator_review'],
      confidence_rules: ['labeled_solicitation_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_solicitation_number'],
    },
    {
      field_id: 'executed_date',
      label: 'Executed Date',
      object_family: 'contract_identity',
      value_type: 'date',
      aliases: ['execution date', 'contract date', 'date signed'],
      states_allowed: ['explicit', 'derived', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['activation', 'decisioning', 'operator_review'],
      confidence_rules: ['execution_clause_date_match', 'signature_block_date_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_executed_date'],
    },
    {
      field_id: 'effective_date',
      label: 'Effective Date',
      object_family: 'contract_identity',
      value_type: 'date',
      aliases: ['effective on', 'date of availability', 'effective as of'],
      states_allowed: ['explicit', 'derived', 'conflicted', 'missing_critical'],
      criticality: 'P2',
      downstream_dependency: ['activation', 'decisioning', 'operator_review'],
      confidence_rules: ['effective_date_clause_match', 'typed_effective_date_match'],
      derivation_rules: ['effective_date_inherits_executed_if_clause_says_so'],
      question_rule_ids: ['confirm_effective_date'],
    },
  ],
  term_model: [
    {
      field_id: 'initial_term_length',
      label: 'Initial Term Length',
      object_family: 'term_model',
      value_type: 'duration',
      aliases: ['term', 'contract term', 'initial term'],
      states_allowed: ['explicit', 'derived', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['activation', 'decisioning', 'operator_review'],
      confidence_rules: ['term_duration_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_initial_term_length'],
    },
    {
      field_id: 'expiration_date',
      label: 'Expiration Date',
      object_family: 'term_model',
      value_type: 'date',
      aliases: ['term end', 'expiration', 'contract end date'],
      states_allowed: ['explicit', 'derived', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['decisioning', 'workflow_generation', 'operator_review'],
      confidence_rules: ['explicit_expiration_match', 'term_end_clause_match'],
      derivation_rules: ['derive_from_execution_or_effective_plus_term'],
      question_rule_ids: ['confirm_derived_expiration_date'],
    },
  ],
  activation_model: [
    {
      field_id: 'activation_trigger_type',
      label: 'Activation Trigger Type',
      object_family: 'activation_model',
      value_type: 'text',
      aliases: ['notice to proceed', 'task order', 'work order', 'declaration trigger'],
      states_allowed: ['explicit', 'conditional', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['activation', 'decisioning', 'workflow_generation', 'operator_review'],
      confidence_rules: ['activation_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['resolve_activation_trigger'],
    },
    {
      field_id: 'authorization_required',
      label: 'Authorization Required',
      object_family: 'activation_model',
      value_type: 'boolean',
      aliases: ['written authorization', 'written approval', 'issued by task order'],
      states_allowed: ['explicit', 'conditional', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['activation', 'decisioning', 'workflow_generation'],
      confidence_rules: ['written_authorization_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_authorization_requirement'],
    },
    {
      field_id: 'performance_start_basis',
      label: 'Performance Start Basis',
      object_family: 'activation_model',
      value_type: 'text',
      aliases: ['commence work', 'start of work', 'performance begins'],
      states_allowed: ['explicit', 'conditional', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['activation', 'decisioning', 'workflow_generation'],
      confidence_rules: ['performance_start_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_performance_start_basis'],
    },
    {
      field_id: 'mobilization_sla',
      label: 'Mobilization SLA',
      object_family: 'activation_model',
      value_type: 'duration',
      aliases: ['mobilize within', 'mobilization deadline', 'respond within'],
      states_allowed: ['explicit', 'conditional', 'conflicted', 'missing_critical'],
      criticality: 'P2',
      downstream_dependency: ['activation', 'workflow_generation', 'operator_review'],
      confidence_rules: ['mobilization_deadline_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_mobilization_deadline'],
    },
  ],
  scope_model: [],
  pricing_model: [
    {
      field_id: 'rate_schedule_present',
      label: 'Rate Schedule Present',
      object_family: 'pricing_model',
      value_type: 'boolean',
      aliases: ['exhibit a', 'unit rate schedule', 'pricing schedule'],
      states_allowed: ['explicit', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['decisioning', 'billing_review', 'workflow_generation'],
      confidence_rules: ['rate_schedule_table_grounded', 'pricing_section_signal'],
      derivation_rules: [],
      question_rule_ids: ['confirm_rate_schedule_presence'],
    },
    {
      field_id: 'rate_schedule_pages',
      label: 'Rate Schedule Pages',
      object_family: 'pricing_model',
      value_type: 'text',
      aliases: ['pricing exhibit pages', 'rate pages'],
      states_allowed: ['explicit', 'conflicted', 'missing_critical'],
      criticality: 'P2',
      downstream_dependency: ['billing_review', 'operator_review'],
      confidence_rules: ['rate_schedule_page_grounding'],
      derivation_rules: [],
      question_rule_ids: ['confirm_rate_schedule_pages'],
    },
    {
      field_id: 'pricing_applicability',
      label: 'Pricing Applicability',
      object_family: 'pricing_model',
      value_type: 'text',
      aliases: ['compensation basis', 'applicable rates', 'pricing trigger'],
      states_allowed: ['explicit', 'conditional', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['decisioning', 'billing_review', 'reimbursement_logic', 'operator_review'],
      confidence_rules: ['compensation_clause_match', 'pricing_scope_alignment'],
      derivation_rules: ['infer_requires_operational_context_if_activation_or_gate_language_present'],
      question_rule_ids: ['resolve_pricing_applicability'],
    },
    {
      field_id: 'contract_ceiling',
      label: 'Contract Ceiling',
      object_family: 'pricing_model',
      value_type: 'currency',
      aliases: ['not to exceed', 'contract cap', 'maximum amount payable'],
      states_allowed: ['explicit', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['decisioning', 'billing_review', 'workflow_generation'],
      confidence_rules: ['nte_clause_match', 'structured_nte_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_contract_ceiling'],
    },
    {
      field_id: 'contract_ceiling_type',
      label: 'Contract Ceiling Type',
      object_family: 'pricing_model',
      value_type: 'text',
      aliases: ['ceiling type', 'not to exceed model', 'rate based ceiling', 'overall ceiling model'],
      states_allowed: ['explicit', 'derived', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['decisioning', 'billing_review', 'workflow_generation'],
      confidence_rules: ['nte_clause_match', 'rate_schedule_nte_clause_match'],
      derivation_rules: ['classify_as_total_rate_based_or_none'],
      question_rule_ids: ['confirm_contract_ceiling'],
    },
    {
      field_id: 'no_guarantee_quantity',
      label: 'No Guarantee Quantity',
      object_family: 'pricing_model',
      value_type: 'boolean',
      aliases: ['no minimum amount of work', 'no guarantee of work', 'no guaranteed quantity'],
      states_allowed: ['explicit', 'conflicted', 'missing_critical'],
      criticality: 'P2',
      downstream_dependency: ['decisioning', 'billing_review', 'operator_review'],
      confidence_rules: ['no_guarantee_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_no_guarantee_quantity'],
    },
    {
      field_id: 'disposal_fee_treatment',
      label: 'Disposal Fee Treatment',
      object_family: 'pricing_model',
      value_type: 'text',
      aliases: ['tipping fee', 'landfill fee', 'pass through disposal'],
      states_allowed: ['explicit', 'conditional', 'conflicted', 'missing_critical'],
      criticality: 'P2',
      downstream_dependency: ['billing_review', 'reimbursement_logic', 'operator_review'],
      confidence_rules: ['pass_through_disposal_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['resolve_disposal_fee_treatment'],
    },
  ],
  documentation_model: [
    {
      field_id: 'monitoring_required',
      label: 'Monitoring Required',
      object_family: 'documentation_model',
      value_type: 'boolean',
      aliases: ['monitoring', 'debris monitor', 'validated by monitor'],
      states_allowed: ['explicit', 'conditional', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['billing_review', 'reimbursement_logic', 'operator_review'],
      confidence_rules: ['monitoring_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_monitoring_requirement'],
    },
  ],
  compliance_model: [
    {
      field_id: 'fema_eligibility_gate',
      label: 'FEMA Eligibility Gate',
      object_family: 'compliance_model',
      value_type: 'boolean',
      aliases: ['FEMA eligible', 'ineligible work', 'reimbursement eligibility'],
      states_allowed: ['explicit', 'conditional', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['decisioning', 'billing_review', 'reimbursement_logic', 'operator_review'],
      confidence_rules: ['fema_gate_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['resolve_fema_eligibility_gate'],
    },
  ],
  payment_model: [
    {
      field_id: 'billing_documentation_required',
      label: 'Billing Documentation Required',
      object_family: 'payment_model',
      value_type: 'boolean',
      aliases: ['load tickets', 'truck certifications', 'tower logs', 'manifests', 'monitoring records'],
      states_allowed: ['explicit', 'conditional', 'conflicted', 'missing_critical'],
      criticality: 'P1',
      downstream_dependency: ['billing_review', 'reimbursement_logic', 'operator_review'],
      confidence_rules: ['billing_support_clause_match'],
      derivation_rules: [],
      question_rule_ids: ['confirm_billing_documentation_requirements'],
    },
  ],
};

export const LANGUAGE_ENGINE_FIELDS_V1_BY_ID = new Map(
  Object.values(LANGUAGE_ENGINE_FIELDS_V1)
    .flat()
    .map((definition) => [definition.field_id, definition] as const),
);
