import {describe,expect,it,vi} from 'vitest';
import {hashCanonical,sha256Hex} from '@/lib/extraction/domain/hash';
import {runForgewingRepositoryPlanGuidance} from '@/lib/forgewing/tasks/repositoryPlanGuidance';
import {buildRepositoryPlanContent,repositoryContentEvidenceId} from '@/lib/repositoryPlanContent';
import {buildRepositoryPlanFoundation,type RepositoryPlanFoundationInput} from '@/lib/repositoryPlanFoundation';
import {prepareRepositoryPlanGuidance} from '@/lib/repositoryPlanGuidance';
import {recordWorkflowRepositoryPlanV2} from '@/lib/server/workflowRepositoryPlanPersistence';
import {recordWorkflowEngineeringReview} from '@/lib/server/workflowEngineeringReview';
import {buildApprovedEngineeringRequest} from '@/lib/approvedEngineeringRequest';
import {buildLinearCapabilityProjection} from '@/lib/linearCapabilityProjection';
import {projectApprovedEngineeringRequestToLinear} from '@/lib/server/linearProjectionDelivery';
import type {WorkflowImplementationPlanArtifact} from '@/lib/workflowImplementationPlan';
import type {VerifiedRepositorySnapshot} from '@/lib/server/repositoryPlanSnapshot';

describe('Phase 11E deterministic end-to-end authority chain',()=>{it('preserves every exact pin through fake provider, persistence, human review, and fake Linear delivery',async()=>{
 const pin={assessmentId:'11111111-1111-4111-8111-111111111111',assessmentVersion:2,reviewId:'22222222-2222-4222-8222-222222222222',reviewVersion:3};const provenance={...pin,sourceSubmissionId:'33333333-3333-4333-8333-333333333333',stepReviewId:'44444444-4444-4444-8444-444444444444',reviewerActorId:'55555555-5555-4555-8555-555555555555',reviewerNotes:null};
 const step={stepId:'step-1',originalClassification:'RULE' as const,effectiveClassification:'RULE' as const,disposition:'modified' as const,provenance,specificationSource:{mode:'reviewed_replacement' as const,sourceField:'workflow_assessment_step_reviews.accepted_specification' as const},implementationReadiness:{state:'blocked_structural' as const,blocker:'rule_definition_is_code' as const},specification:{plainLanguageRule:'PRIVATE-INTAKE-SENTINEL must not project',requiredFacts:['evidence'],conditionType:'presence_check' as const,expectedEvidence:['source'],expectedOutcome:'present',userDescribedExceptions:[],unresolvedAssumptions:[]}};
 const p1Envelope={domain:'eightforge.implementation-plan' as const,schemaVersion:1 as const,authority:'non_authoritative' as const,executable:false as const,grantsExecutionAuthority:false as const,source:{pin,effectiveReviewedSpecificationDigestSha256:'d'.repeat(64)},plannedSteps:[step],rejectedSteps:[]};const planV1={...p1Envelope,digest:{algorithm:'sha256',encoding:'recursive-key-sorted-json-v1',value:hashCanonical(p1Envelope)}} as WorkflowImplementationPlanArtifact;
 const commit='a'.repeat(40);const catalogDigest='e'.repeat(64);const snapshot={repositoryUrl:'https://github.com/example/repository',objectFormat:'sha1',commitSha:commit,branchName:'main',worktreeDirty:false,untrackedPolicy:'excluded_from_trusted_manifest',submoduleStatus:{state:'none'}} as VerifiedRepositorySnapshot;const inspected={filePath:'lib/rules/example.ts',commitSha:commit,blobSha:'b'.repeat(40),classification:'RULE' as const};const foundation=buildRepositoryPlanFoundation({trustedPlanV1:planV1,repositorySnapshot:snapshot,repositoryEvidenceCatalogDigestSha256:catalogDigest,manifest:[inspected],evidence:[{filePath:inspected.filePath,commitSha:commit,classification:'RULE',evidenceKind:'authored_rule',reason:'Existing seam'}]} as RepositoryPlanFoundationInput);if(!foundation.ok)throw new Error(foundation.code);
 const content='export const value = 1;\n';const evidenceId=repositoryContentEvidenceId(inspected);const bundle=buildRepositoryPlanContent({foundation:foundation.artifact,classification:'RULE',collected:[{evidenceId,mode:'100644',contentEncoding:'utf8',byteLength:new TextEncoder().encode(content).byteLength,contentSha256:sha256Hex(content),content}]});if(!bundle.ok)throw new Error(bundle.code);const prepared=prepareRepositoryPlanGuidance({trustedPlanV1:planV1,foundation:foundation.artifact,content:bundle.artifact});if(!prepared.ok)throw new Error(prepared.code);const candidate=prepared.artifact.steps[0]!.recommendationCandidates[0]!;
 const output=JSON.stringify({classification:'RULE',stepGuidance:[{stepId:'step-1',...candidate,capabilitySummary:'Reuse evidence rule',summary:'Reuse the existing bounded seam.',evidenceRefs:[evidenceId],existingSeamEvaluation:'existing_seam_cited',architectureRisks:[],regressionGates:[{gate:'typecheck'}],stopConditions:[],unresolvedQuestions:[]}],operatorDecisionSuggestions:[],unresolvedGlobalQuestions:[],insufficientEvidence:[]});const generated=await runForgewingRepositoryPlanGuidance(prepared.artifact,{config:{enabled:true,model:'fake-claude',timeoutMs:60000,maxOutputTokens:8000},provider:async()=>output});if(generated.status!=='completed'||!generated.rawProviderEvidence)throw new Error(generated.status);
 const planRunId='66666666-6666-4666-8666-666666666666';const persisted=await recordWorkflowRepositoryPlanV2(generated.planV2,generated.rawProviderEvidence,{admin:{rpc:vi.fn().mockResolvedValue({data:{plan_v2_run_id:planRunId,raw_evidence_id:'77777777-7777-4777-8777-777777777777',inserted:true},error:null})}});expect(persisted.status).toBe('recorded');
 expect(generated.planV2.source.repositoryEvidenceCatalogDigestSha256).toBe(catalogDigest);process.env.INTERNAL_ORCHESTRATOR_ALLOWED_EMAILS='reviewer@example.com';const actor={id:'88888888-8888-4888-8888-888888888888',email:'reviewer@example.com',role:null};const reviewResult=await recordWorkflowEngineeringReview({planV2RunId:planRunId,planV2DigestSha256:generated.planV2.digest.value,recommendationId:candidate.recommendationId,disposition:'accepted',capabilityScope:'workflow_specific',reviewerRationale:'Approved for backlog only.'},actor,{admin:{rpc:vi.fn().mockResolvedValue({data:{review_id:'99999999-9999-4999-8999-999999999999',review_version:1,repository_commit_sha:commit,inserted:true},error:null})}});if(!reviewResult.ok)throw new Error(reviewResult.code);const approved=buildApprovedEngineeringRequest(generated.planV2,reviewResult.review);if(!approved.ok)throw new Error(approved.code);
 const bindings=[{evidenceRef:evidenceId,filePath:inspected.filePath,blobSha:inspected.blobSha,commitSha:commit}];const projection=buildLinearCapabilityProjection(approved.request,bindings);if(!projection.ok)throw new Error(projection.code);const client={createIssue:vi.fn().mockResolvedValue({id:'linear-id',identifier:'EF-1'}),findProjectedIssueByIdempotencyKey:vi.fn()};const delivery=await projectApprovedEngineeringRequestToLinear({planV2RunId:planRunId,planV2DigestSha256:generated.planV2.digest.value,recommendationId:candidate.recommendationId,reviewId:reviewResult.review.reviewId,reviewVersion:1,evidenceBindings:bindings},{email:actor.email,role:null},{admin:{rpc:vi.fn(async(name:string)=>name==='claim_linear_projection_delivery'?{data:{correlation_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',claim_token:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',claim_status:'acquired',linear_issue_id:null,linear_issue_identifier:null},error:null}:{data:null,error:null})},configuration:{projectId:'project-id',client},readApproved:vi.fn().mockResolvedValue(approved),readPlan:vi.fn().mockResolvedValue({ok:true,planV2:generated.planV2})});expect(delivery.status).toBe('projected');expect(generated.planV2.authority).toBe('non_authoritative');expect(approved.request.authorizes).toBe('backlog_projection');expect(projection.projection.linearAuthority).toBe('none');expect(JSON.stringify(projection.projection)).not.toContain('PRIVATE-INTAKE-SENTINEL');expect(generated.planV2.source.reviewPin).toEqual(pin);expect(approved.request.source.repositoryCommitSha).toBe(commit);expect(client.createIssue).toHaveBeenCalledTimes(1);
});});
