'use client';
import { useState } from 'react';
import type { RepositoryPlanGuidanceArtifact } from '@/lib/repositoryPlanGuidance';
import type { EngineeringCapabilityScope, ModifiedEngineeringScope } from '@/lib/workflowEngineeringReview';

export type EngineeringReviewPacket={workflowIdentity:string;planV1State:string;repositoryCommitSha:string;repositoryFresh:boolean;planV2RunId:string;planV2DigestSha256:string;classification:'RULE'|'VERIFY'|'EXTRACT'|'RECOVER'|'HUMAN'|'ADVISORY';recommendation:RepositoryPlanGuidanceArtifact['recommendations'][number];resolvedEvidence:readonly {evidenceRef:string;filePath:string;blobSha:string}[];operatorSuggestion?:{decisionType:string;suggestedValue:string}|null};
export function EngineeringRecommendationReview({packet,accessToken,onRecorded}:{packet:EngineeringReviewPacket;accessToken:string;onRecorded?:()=>void}){
 const [disposition,setDisposition]=useState<'accepted'|'modified'|'rejected'|'deferred'>('deferred'); const [capabilityScope,setCapabilityScope]=useState<EngineeringCapabilityScope>('workflow_specific'); const [rationale,setRationale]=useState(''); const [replacement,setReplacement]=useState<ModifiedEngineeringScope|null>(null); const [status,setStatus]=useState<string>('');
 async function submit(){setStatus('Recording…');const body={planV2RunId:packet.planV2RunId,planV2DigestSha256:packet.planV2DigestSha256,recommendationId:packet.recommendation.recommendationId,disposition,reviewerRationale:rationale,...(disposition==='accepted'||disposition==='modified'?{capabilityScope}:{}),...(disposition==='modified'?{modifiedScope:replacement}: {})};const response=await fetch('/api/internal/repository-engineering-reviews',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify(body)});setStatus(response.ok?'Review recorded':'Review could not be recorded');if(response.ok)onRecorded?.();}
 const r=packet.recommendation;
 return <section className="space-y-5 rounded-xl border border-white/10 p-5" aria-label="Engineering recommendation review">
  <header><p className="text-xs text-[var(--ef-text-muted)]">{packet.workflowIdentity} · Plan V1 {packet.planV1State}</p><h2 className="text-lg font-semibold">{r.capabilitySummary}</h2><p className="font-mono text-xs">{packet.repositoryCommitSha} · {packet.repositoryFresh?'Current':'Stale repository context'}</p></header>
  <dl className="grid gap-2 text-sm"><div><dt>Classification</dt><dd>{packet.classification}</dd></div><div><dt>Forgewing recommendation</dt><dd>{r.summary}</dd></div><div><dt>Architecture risks</dt><dd>{r.architectureRisks.join('; ')||'None recorded'}</dd></div><div><dt>Regression gates</dt><dd>{r.regressionGates.map(g=>g.gate).join(', ')||'None'}</dd></div><div><dt>Stop conditions</dt><dd>{r.stopConditions.join(', ')||'None'}</dd></div><div><dt>Unresolved questions</dt><dd>{r.unresolvedQuestions.join('; ')||'None'}</dd></div></dl>
  <div><h3 className="font-semibold">Evidence</h3>{packet.resolvedEvidence.map(e=><p key={e.evidenceRef} className="font-mono text-xs">{e.evidenceRef} · {e.filePath} · {e.blobSha}</p>)}</div>
  {packet.operatorSuggestion&&<aside className="rounded border border-amber-500/40 p-3"><strong>Human decision required</strong><p>Suggestion only. Requires operator confirmation.</p><p>{packet.operatorSuggestion.decisionType}: {packet.operatorSuggestion.suggestedValue}</p></aside>}
  <label>Disposition<select value={disposition} onChange={e=>setDisposition(e.target.value as typeof disposition)}><option value="accepted">Accepted</option><option value="modified">Modified</option><option value="rejected">Rejected</option><option value="deferred">Deferred</option></select></label>
  {(disposition==='accepted'||disposition==='modified')&&<label>Capability scope<select value={capabilityScope} onChange={e=>setCapabilityScope(e.target.value as EngineeringCapabilityScope)}><option value="client_specific">Client-specific</option><option value="workflow_specific">Workflow-specific</option><option value="reusable_platform_capability">Reusable platform capability</option></select></label>}
  {disposition==='modified'&&<label>Human-reviewed replacement scope<textarea aria-label="Human-reviewed replacement scope JSON" onChange={e=>{try{setReplacement(JSON.parse(e.target.value));}catch{setReplacement(null);}}}/></label>}
  <label>Reviewer rationale<textarea value={rationale} maxLength={4000} onChange={e=>setRationale(e.target.value)}/><small>This note may be included in the engineering backlog projection.</small></label>
  <button type="button" disabled={!rationale.trim()||(disposition==='modified'&&!replacement)} onClick={submit}>Record engineering review</button><p role="status">{status}</p>
 </section>;
}
