-- Phase 15 adversarial remediation: a diagnostic id may be replayed for the
-- same immutable outcome, but it must not identify different outcome content.
-- Snapshot id remains observational and observed_at is generated by the table.

CREATE OR REPLACE FUNCTION public.record_forgewing_recovery_generation_outcome(
  p_organization_id uuid,
  p_source_document_id uuid,
  p_source_artifact_id uuid,
  p_extraction_snapshot_id text,
  p_physical_page_number integer,
  p_page_representation_digest text,
  p_diagnostic_id text,
  p_recovery_type text,
  p_outcome_code text,
  p_sanitized_reason text,
  p_provider_invoked boolean,
  p_candidate_ids jsonb
) RETURNS TABLE(outcome_row_id uuid, inserted boolean)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_inserted_id uuid;
  v_existing public.forgewing_recovery_generation_outcomes%ROWTYPE;
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION 'service_role required' USING ERRCODE = '42501';
  END IF;
  IF NOT EXISTS (
    SELECT 1
    FROM public.extraction_source_artifacts artifact
    JOIN public.documents document ON document.id = artifact.source_document_id
    WHERE artifact.id = p_source_artifact_id
      AND artifact.source_document_id = p_source_document_id
      AND artifact.organization_id = p_organization_id
      AND document.organization_id = p_organization_id
  ) THEN
    RAISE EXCEPTION 'recovery generation outcome source binding mismatch'
      USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.forgewing_recovery_generation_outcomes (
    organization_id, source_document_id, source_artifact_id, extraction_snapshot_id,
    physical_page_number, page_representation_digest, diagnostic_id, recovery_type,
    outcome_code, sanitized_reason, provider_invoked, candidate_ids)
  VALUES (
    p_organization_id, p_source_document_id, p_source_artifact_id, p_extraction_snapshot_id,
    p_physical_page_number, p_page_representation_digest, p_diagnostic_id, p_recovery_type,
    p_outcome_code, p_sanitized_reason, p_provider_invoked, p_candidate_ids)
  ON CONFLICT (organization_id, diagnostic_id) DO NOTHING
  RETURNING id INTO v_inserted_id;

  IF v_inserted_id IS NOT NULL THEN
    RETURN QUERY SELECT v_inserted_id, true;
    RETURN;
  END IF;

  SELECT * INTO STRICT v_existing
  FROM public.forgewing_recovery_generation_outcomes
  WHERE organization_id = p_organization_id AND diagnostic_id = p_diagnostic_id;
  IF v_existing.source_document_id IS DISTINCT FROM p_source_document_id
     OR v_existing.source_artifact_id IS DISTINCT FROM p_source_artifact_id
     OR v_existing.physical_page_number IS DISTINCT FROM p_physical_page_number
     OR v_existing.page_representation_digest IS DISTINCT FROM p_page_representation_digest
     OR v_existing.recovery_type IS DISTINCT FROM p_recovery_type
     OR v_existing.outcome_code IS DISTINCT FROM p_outcome_code
     OR v_existing.sanitized_reason IS DISTINCT FROM p_sanitized_reason
     OR v_existing.provider_invoked IS DISTINCT FROM p_provider_invoked
     OR v_existing.candidate_ids IS DISTINCT FROM p_candidate_ids THEN
    RAISE EXCEPTION 'recovery generation diagnostic identity collision'
      USING ERRCODE = '23505';
  END IF;
  RETURN QUERY SELECT v_existing.id, false;
END $$;

REVOKE ALL ON FUNCTION public.record_forgewing_recovery_generation_outcome(
  uuid,uuid,uuid,text,integer,text,text,text,text,text,boolean,jsonb)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.record_forgewing_recovery_generation_outcome(
  uuid,uuid,uuid,text,integer,text,text,text,text,text,boolean,jsonb)
  TO service_role;
