// ASK ROUTER - deterministic signal data only. No truth production.

export type IntentGroup =
  | 'approval_execution_state'
  | 'invoice_support'
  | 'contract_authority'
  | 'ticket_validation'
  | 'review_audit_state'
  | 'portfolio_project_status';

export interface IntentSignal {
  keywords: string[];
  phrases: string[];
  weight: number;
}

export const INTENT_CLASSIFICATION_MAP: Record<IntentGroup, IntentSignal[]> = {
  approval_execution_state: [
    {
      keywords: [
        'approve',
        'approval',
        'approved',
        'ready',
        'blocked',
        'blocking',
        'preventing',
        'release',
        'payment',
        'gate',
        'proceed',
        'forward',
        'action',
        'execution',
        'exceptions',
      ],
      phrases: [
        'can we approve',
        'ready for invoice approval',
        'ready for approval',
        'what is blocking',
        'what is preventing',
        'next best action',
        'next action',
        'move forward',
        'payment release',
        'execution item',
        'open tickets',
        'approved with exceptions',
        'action before approval',
        'release payment',
      ],
      weight: 2,
    },
  ],
  invoice_support: [
    {
      keywords: [
        'invoice',
        'supported',
        'unsupported',
        'support',
        'exposure',
        'billed',
        'amount',
        'amounts',
        'total',
        'exception',
        'costs',
        'rate',
        'rates',
        'ceiling',
        'nte',
      ],
      phrases: [
        'invoice support',
        'fully supported',
        'not supported',
        'unsupported ticket costs',
        'at risk',
        'invoice amount',
        'invoice amounts',
        'invoice exposure',
        'where did',
        'come from',
        'correct contract rates',
        'contract rate table',
        'approaching contract ceiling',
      ],
      weight: 2,
    },
    {
      keywords: ['coverage'],
      phrases: [],
      weight: 1,
    },
  ],
  contract_authority: [
    {
      keywords: [
        'contract',
        'governing',
        'amendment',
        'exhibit',
        'schedule',
        'replace',
        'replaced',
        'older',
        'newer',
        'conflicting',
        'facts',
        'tipping',
        'billable',
        'documentation',
        'monitoring',
        'gps',
        'photos',
        'loads',
        'private',
        'property',
        'fema',
        'reimbursable',
        'performance',
        'bond',
        'funding',
        'contingency',
        'quantity',
        'authority',
      ],
      phrases: [
        'which contract is governing',
        'governing contract',
        'rate schedule',
        'amendment or exhibit',
        'replace an older',
        'conflicting facts',
        'tipping fees',
        'billable under this contract',
        'documentation is required',
        'required for payment',
        'monitoring required',
        'federal compliance',
        'private property',
        'performance bond',
        'fema reimbursable',
        'funding is denied',
        'funding contingency',
        'no guaranteed quantity',
        'daily reconciliation',
      ],
      weight: 2,
    },
  ],
  ticket_validation: [
    {
      keywords: [
        'ticket',
        'tickets',
        'correction',
        'correct',
        'missing',
        'disposal',
        'site',
        'material',
        'cyd',
        'tonnage',
        'mileage',
        'rate-code',
        'reviewer',
        'unresolved',
        'mismatches',
      ],
      phrases: [
        'tickets need correction',
        'need correction',
        'missing disposal site',
        'missing disposal',
        'rate code mismatches',
        'rate-code mismatches',
        'unresolved by reviewer',
        'tickets are unresolved',
      ],
      weight: 2,
    },
  ],
  review_audit_state: [
    {
      keywords: [
        'review',
        'reviewed',
        'warnings',
        'confirmed',
        'overridden',
        'override',
        'human',
        'inspect',
        'inspection',
        'changed',
        'change',
        'baseline',
      ],
      phrases: [
        'changed since the last review',
        'last review',
        'documents still need review',
        'marked reviewed',
        'producing warnings',
        'manually confirmed',
        'overridden by a human',
        'inspect first',
        'operator inspect',
        'findings were overridden',
        'override reason',
      ],
      weight: 2,
    },
  ],
  portfolio_project_status: [
    {
      keywords: [
        'portfolio',
        'projects',
        'cross-project',
        'workspace',
        'aggregate',
        'stale',
        'snapshots',
        'rank',
        'first',
        'patterns',
        'issues',
      ],
      phrases: [
        'across all projects',
        'which projects',
        'projects are blocked',
        'projects are ready',
        'ready for approval',
        'need review first',
        'issues are happening most',
        'total at-risk amount across',
        'stale validation snapshots',
        'approaching contract ceiling',
      ],
      weight: 2,
    },
  ],
};

export const INTENT_GROUP_LABELS: Record<IntentGroup, { label: string; example: string }> = {
  approval_execution_state: {
    label: 'Approval and execution state',
    example: 'What is blocking approval?',
  },
  invoice_support: {
    label: 'Invoice support and exposure',
    example: 'Which invoice amounts are unsupported?',
  },
  contract_authority: {
    label: 'Contract authority and requirements',
    example: 'Which contract is governing?',
  },
  ticket_validation: {
    label: 'Ticket validation',
    example: 'Which tickets need correction?',
  },
  review_audit_state: {
    label: 'Review and audit state',
    example: 'What changed since the last review?',
  },
  portfolio_project_status: {
    label: 'Portfolio project status',
    example: 'Which projects are blocked right now?',
  },
};
